### ISSUE TITLE
OTA Package isn't Installing

### ISSUE THREAD

**Issue by Machad3x** [pjgowtham/recovery_device_oplus_sm8475#1]
Trying installing OTA Full package in Oneplus 10 Pro, but giving error.

![photo_2023-08-10_08-15-24](https://github.com/pjgowtham/recovery_device_oplus_ferrarri/assets/39349948/87c2a523-c1f4-415b-99ac-fb60093d6b7e)

**Comment by pjgowtham** [comment]
Can you give me the recovery log which you can obtain using this command

adb pull /tmp/recovery.log

**Comment by Machad3x** [comment]
> adb pull /tmp/recovery.log

[recovery.log](https://github.com/pjgowtham/recovery_device_oplus_ferrarri/files/12313617/recovery.log)

**Comment by pjgowtham** [comment]
You can run this command in twrp

`resetprop ro.twrp.target.devices OP516EL1,OP516FL1`

and re-attempt flashing

I'll fix this next build

**Comment by Machad3x** [comment]
Flawless working, thanks dev!
