### ISSUE TITLE
Error applying update: 7 (ErrorCode: :kInstallDeviceOpenError)

### ISSUE THREAD

**Issue by C1014** [pjgowtham/recovery_device_oplus_sm8475#2]
Tried to install the stock rom to test but I got this error 
![Screenshot_2023-08-10-09-39-44](https://github.com/pjgowtham/recovery_device_oplus_ferrarri/assets/60809540/2f0aa9ae-ee53-4c18-a707-778f70020dce)

Log: 
[recovery.log](https://github.com/pjgowtham/recovery_device_oplus_ferrarri/files/12314044/recovery.log)

**Comment by pjgowtham** [comment]
By any chance you ran
`fastboot erase super `command previously?

was your device in a working state before flashing?

**Comment by C1014** [comment]
Yes, it is working. But what I did days ago is to install custom rom to test but decided to go back to stock by using fastboot enhance which still works lol.

**Comment by pjgowtham** [comment]
Can you share recovery.log after attempting to flash?

**Comment by pjgowtham** [comment]
It could be because metadata isn't mounted which could happen if you had previously mounted or unmounted it before flashing

Can you reboot to TWRP and flash without mounting/re-mounting partitions

**Comment by pjgowtham** [comment]
I think I am wrong. Will look into this log and get back in sometime. I think fastboot enhance could have done a poor job previously

**Comment by pjgowtham** [comment]
[super_empty.img.zip](https://github.com/pjgowtham/recovery_device_oplus_ferrarri/files/12314727/super_empty.img.zip)

`fastboot wipe-super super_empty.img`

Run this in bootloader and then try flashing the ota

**Comment by C1014** [comment]
Awesome! it worked. I have also put the command from the other issue though just in case haha
![Screenshot_2023-08-10-18-23-02](https://github.com/pjgowtham/recovery_device_oplus_ferrarri/assets/60809540/54e1b12b-bb07-407b-8d70-fc2a26a15c6a)
