### ISSUE TITLE
Oneplus 10 Pro - Error while backing up EFS partitions

### ISSUE THREAD

**Issue by I3elphegor** [pjgowtham/recovery_device_oplus_sm8475#3]
![Screenshot_2023-08-22-08-00-07](https://github.com/pjgowtham/recovery_device_oplus_ferrarri/assets/56094270/80c97627-d745-4da4-b619-717328855f65)

**Comment by pjgowtham** [comment]
Thanks. will be fixed next build.

**Comment by pjgowtham** [comment]
https://github.com/pjgowtham/recovery_device_oplus_ferrarri/releases/download/twrp-3.7.0_12-0_LOCAL-20230826-08-ferrarri/twrp-3.7.0_12-0_LOCAL-20230826-08-ferrarri.img
