### ISSUE TITLE
Pls add support Realme Neo5 SE

### ISSUE THREAD

**Issue by master88wi** [pjgowtham/recovery_device_oplus_sm8475#4]
Pls add support Realme Neo5 SE (RMX3700)
https://github.com/tosasitill/android_device_realme_RMX3700
it has a similar partition structure to the Realme GT Neo 5. 
I'm ready to be a tester
The difference is the processor. 
Which, although different, is similar to the processor from Realme GT Neo 5

the same on the processor, for example neo5se

POCO F5 similar another model where there is recovery
https://github.com/Kyuofox-Studio/android_kernel_xiaomi_sm7475
https://github.com/Pzqqt/android_kernel_xiaomi_marble

**Comment by pjgowtham** [comment]
I think realme Neo 5 SE is already supported
