### ISSUE TITLE
Error applying update: 7 (ErrorCode: :kInstallDeviceOpenError)

### ISSUE THREAD

**Issue by Machad3x** [pjgowtham/recovery_device_oplus_sm8475#5]
![Screenshot_2024-08-30-11-10-27](https://github.com/user-attachments/assets/771c2c6c-7da7-42a1-8fc1-49453b51b466)

Trying to install custom roms or stock returning error.

Tried flashing empty super, but no success.

[recovery.log](https://github.com/user-attachments/files/16819649/recovery.log)

**Comment by pjgowtham** [comment]
I've dropped TWRP completely. You can achieve the same things with lineage or other similar recoveries
